spring:
  application:
    name: proxy-server

server:
  port: 8762

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    product-service:
      stripPrefix: false
      path: /product-service/**
      serviceId: product-service
    order-service:
      stripPrefix: false
      path: /order-service/**
      serviceId: order-service

ribbon:
  ConnectTimeout: 10000000
  ReadTimeout: 10000000