spring:
  application:
    name: order-service
  cloud:
    stream:
      bindings:
        orders-input:
          destination: orders
          group: order-service
        orders-output:
          destination: orders
          group: order-service
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

server:
  port: 8081
  servlet:
    context-path: /order-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

stripe:
  api:
    key: ${STRIPE_API_KEY}
    secret: ${STRIPE_API_SECRET}