spring:
  application:
    name: order-processing-service
  cloud:
    stream:
      bindings:
        orders-input:
          destination: orders
          group: order-processing-service
        orders-output:
          destination: orders
          group: order-processing-service

server:
  port: 8082